# Generated by Django 4.2.11 on 2024-04-15 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_getintouch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='getintouch',
            new_name='Contactus',
        ),
    ]
