# Generated by Django 4.2.11 on 2024-04-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_contact_email_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='types',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
