# Generated by Django 4.2.11 on 2024-04-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='category',
            field=models.CharField(choices=[('SH', 'Shoes'), ('S', 'Shirt'), ('J', 'Jeans')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
