# Generated by Django 4.2.11 on 2024-04-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_wishlist_category_wishlist_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='choser',
            field=models.BooleanField(default=False),
        ),
    ]
