# Generated by Django 4.2.11 on 2024-04-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_wishlist_choser_item_choser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='choser',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='choser',
            field=models.BooleanField(default=False),
        ),
    ]
