# Generated by Django 4.2.11 on 2024-04-22 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_remove_item_choser_wishlist_choser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='choser',
        ),
    ]
